### PR TITLE
Add velocitas uprotocol package repo

### PR DESCRIPTION
**Pull request by dennismeister93**
Adds a new repository for the velocitas uprotocol toolchain package.

### CODE REVIEW

**Comment by dennismeister93** [comment]
Hi @netomi , can you support here? :) thank you in advance!

**Comment by netomi** [comment]
I am currently on vacation but could a project lead approve?

**Review by gkreyssing — APPROVED** [review]
LGTM!

**Review by eclipsewebmaster — APPROVED** [review]

**Review by heurtematte — APPROVED** [review]

**Comment by heurtematte** [comment]
Changes are live!

**Pull request merged**
