### PR TITLE
Add velocitas-lib repo

### PR DESCRIPTION
**Pull request by doosuu**
Add velocitas-lib repsitory

### CODE REVIEW

**Comment by netomi** [comment]
Can I get an approval from a project lead as well please? Or do you have some link to the mailinglist archive that approves this change? @ariexi @gkreyssing 

Otherwise LGTM

**Review by ariexi — APPROVED** [review]
LGTM

**Comment by netomi** [comment]
change has been applied, repo has been created.

**Comment by gkreyssing** [comment]
LGTM

**Review by kse3hi — COMMENTED** [review]
LGTM

**Pull request merged**
