### PR TITLE
Add discussions into velocitas-docs

### PR DESCRIPTION
**Pull request by kse3hi**
Add discussions into velocitas-docs and remove it from other repos

### CODE REVIEW

**Comment by netomi** [comment]
I will approve this change as is as it is very minor and looks reasonable, please let me know how you would like to have approvals for your project in the future. Shall at least another committer approve, or project leads? cc @ariexi @gkreyssing

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
change has been applied.

**Comment by kse3hi** [comment]
Thank you @netomi 
I think we shall keep approval from one additional Committer + one project manager.

Of course for reasonable and small PR only one Committer approval should be enough.

What do yo think @gkreyssing ?

**Review by gkreyssing — COMMENTED** [review]
LGTM

**Pull request merged**
